// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGeQf-rp_YB_9f-M_LGUNJqJuezLF9KMo',
    appId: '1:763661095236:web:e3657c7fb15a299e8b0711',
    messagingSenderId: '763661095236',
    projectId: 'clean-architecture-pract-56f72',
    authDomain: 'clean-architecture-pract-56f72.firebaseapp.com',
    storageBucket: 'clean-architecture-pract-56f72.firebasestorage.app',
    measurementId: 'G-2H0WVZ293B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdN-joLj8lh-r-HVN9FG4Mk5Sd7G9cb_U',
    appId: '1:763661095236:android:d51b7aeaf1073f0d8b0711',
    messagingSenderId: '763661095236',
    projectId: 'clean-architecture-pract-56f72',
    storageBucket: 'clean-architecture-pract-56f72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGRuVQsw6K6rlKD6JnInC7jZFfeSgrQ6M',
    appId: '1:763661095236:ios:811c1e7fae84c48b8b0711',
    messagingSenderId: '763661095236',
    projectId: 'clean-architecture-pract-56f72',
    storageBucket: 'clean-architecture-pract-56f72.firebasestorage.app',
    iosBundleId: 'com.example.cleanArchitecturePractice',
  );
}
